### ISSUE TITLE
installing this plugin removes actionMenus from sanity-plugin-intl-input

### ISSUE THREAD

**Issue by kimvuVarner** [sanity-io/sanity-plugin-content-calendar#20]
![image](https://user-images.githubusercontent.com/89914537/134501360-ccb04e32-f331-4b9b-9b11-00e4f18d83ee.png)
these actions is from sanity-plugin-intl-input and is used for translations/ localization. It dissapears when i install with "sanity install content-calendar". 

Would be nice to be able to use both without losing these actions. The plugin may overwrite every action from plugins perhaps?

**Comment by runeb** [comment]
We agree. Unfortunately the API for adding custom actions is not stackable at the moment, so you'll need to manually add the actions from this and from that plugin. This plugin has documentation on how to do this and the other plugin should also provide that. If not, then please request it.
