### ISSUE TITLE
trying to make custom document actions gives error

### ISSUE THREAD

**Issue by kimvuVarner** [sanity-io/sanity-plugin-content-calendar#21]
```
//import the default document actions
import defaultResolve from 'part:@sanity/base/document-actions';
import { addActions } from 'sanity-plugin-content-calendar/src/register';

import { CustomPublishAction } from './actions/publishIntlAndCalendar';

export default function resolveDocumentActions(props) {
  const actions = [...defaultResolve(props), CustomPublishAction];
  return addActions(props, actions);
}

```
It looks like the addActions uses somes spread operator, why is it causing problems? is this babel-loader related and how do I fix this?

Error in ../node_modules/sanity-plugin-content-calendar/src/register.js
Module parse failed: Unexpected token (15:4)
You may need an appropriate loader to handle this file type.
|
|   const result = DeleteAction({
|     ...params,
|     onComplete
|   })

**Comment by runeb** [comment]
Please test this on the lastest version if it is still a problem
