### ISSUE TITLE
_i18n_locale field is missing from the scheduling when using sanity-plugin-intl-input

### ISSUE THREAD

**Issue by emilpriverrc** [sanity-io/sanity-plugin-content-calendar#22]
Hi,

I am using `sanity-plugin-intl-input` to i18n my Sanity. When using "sanity-plugin-content-calendar" does not the package create the page with _i18n_locale information. Which I totally understand why. Everything works fine if I create the page and then schedule changes but we want to be able to schedule a page to be published later on. Is there any way that we could publish a page later on with the _i18n_locale information? Ex a hook that is called when a page is published.

Is this something we should do when we call the API route which handles the creation of the page?

**Comment by runeb** [comment]
See #20 on interop with that plugin
