### ISSUE TITLE
Calendar Plugin creates duplicate buttons

### ISSUE THREAD

**Issue by bigfatbird** [sanity-io/sanity-plugin-content-calendar#23]
<img width="236" alt="Screenshot 2021-12-02 at 13 50 35" src="https://user-images.githubusercontent.com/1159341/144426791-5462ef80-1cc6-4470-9c5f-f4153c7c8cca.png">

I installed this plugin and now there are duplicate publish and delete buttons in the editor for blog posts.

**Comment by runeb** [comment]
Thank you. This issue is fixed in https://github.com/sanity-io/sanity-plugin-content-calendar/releases/tag/v1.2.3

**Comment by bigfatbird** [comment]
Cool, thank you 🙂
