### ISSUE TITLE
Plugin crashes on document delete

### ISSUE THREAD

**Issue by danielmartinsen** [sanity-io/sanity-plugin-content-calendar#24]
If you have a document, e.g. a news article, scheduled at a time and then delete it without clicking unschedule, crashes the plugin. The only way to fix it is to find the document id (e.g. with help of vision and *[_type=="schedule.metadata"]), navigate to it via url and then click unschedule.

The "Delete" button should also unpublish the document before deleting.

**Comment by runeb** [comment]
Hello @danielmartinsen and thank you for your issue report.

I cannot reproduce this issue, using the latest version. Could you describe in more detail the steps needed to be taken to reproduce the bug? A better understanding of how and where it crashes the plugin will also help in diagnosing this.

Thanks again.

**Comment by danielmartinsen** [comment]
Hi! It has been a few days since the plugin crashed now, and when I tried again it all worked fine. Don't know how, and the version is not updated, no must have been something strange must have happened there. I will let you know if I encounter the issue again.

**Comment by runeb** [comment]
I actually managed to reproduce this now by deleting the document directly via the API. Fix is on the way. Thanks again.
