### ISSUE TITLE
See calendar but not my custom type?

### ISSUE THREAD

**Issue by tonybhz** [sanity-io/sanity-plugin-content-calendar#28]
I ran this:
```
sanity install content-calendar
```

My config (config/content-calendar.json) looks like this:
{
  "types": [
    {
      "type": "blog",
      "field": "date"
    }
  ],
  "calendar": {
    "event": {
      "dateFormat": "YYYY-MM-DD",
      "timeFormat": "hh:mm a"
    }
  },
  "filterWarnings": [{}]
}

But nothing show's up but a blank calendar, what am I missing?

**Comment by jkaliski** [comment]
Hello Tony, I ran into a similar problem, did you find any solution?

**Comment by tonybhz** [comment]
@jkaliski - It works once you've ran the cron job to publish the pending posts.
