### ISSUE TITLE
Can not see any calendar entries

### ISSUE THREAD

**Issue by jkaliski** [sanity-io/sanity-plugin-content-calendar#29]
After installing plugin and configuring .json file I still can not see any of my entries in calendar. Am I missing something? This is my file. I have 2 schemas: "watch" for my videos and "post" for my blog entries. No fields are missing, no error is being thrown.

```
{
    "types": [
        {
            "type": "watch",
            "field": "publishedAt",
            "titleField": "seriesTitle"
        },
        {
            "type": "post",
            "field": "publishedAt",
            "titleField": "title"
        }
    ],
    "calendar": {
        "event": {
            "dateFormat": "MMMM, dd yyyy",
            "timeFormat": "hh:mm a",
            "showAuthor": "false"
        }
    },
    "filterWarnings": [{}]
}
```

**Comment by pavanpodila** [comment]
Same problem at my end...after the latest update

**Comment by jkaliski** [comment]
Kinda made it work after a while. Create a bunch of future posts and it will show Schedule button instead of publish.

**Comment by straube** [comment]
Same over here. I just installed the plugin. I was able to schedule a post but it doesn't show up in the calendar.

**Comment by straube** [comment]
I checked the browser console for errors and figured out what was happening in my case. I had to define the title field for the document type I was trying to add to the calendar, this way:

```
{
  "types": [
    {
        "type": "blogPost",
        "field": "tabs.publishedAt",
        "titleField": "tabs.seo.title"
    }
  ],
  "filterWarnings": [{}]
}
```

**Comment by nodefcon** [comment]
> I checked the browser console for errors and figured out what was happening in my case. I had to define the title field for the document type I was trying to add to the calendar, this way:
> 
> ```
> {
>   "types": [
>     {
>         "type": "blogPost",
>         "field": "tabs.publishedAt",
>         "titleField": "tabs.seo.title"
>     }
>   ],
>   "filterWarnings": [{}]
> }
> ```

As you mentioned, we just have to specify a title... Thank you so much, you are our hero!
