### ISSUE TITLE
Time zones

### ISSUE THREAD

**Issue by runeb** [sanity-io/sanity-plugin-content-calendar#7]
Either add, or wait for time zone selector in Studio native datetime input. It is important to be able to be specific about times. The Studio currently (feb 2021) does not have time zone selector in its datetime input component. Either we'll wait for that to land in the Studio, or we can add a custom input component for use with this plugin.

**Comment by rlau1115** [comment]
Any update on this?

**Comment by runeb** [comment]
Hello @rlau1115. We are in the process of creating a whole new scheduled publishing plugin which will include timezones, so look out for that!
