### ISSUE TITLE
Used property "fetch" on versionless client - this is deprecated.

### ISSUE THREAD

**Issue by alexeygolev** [sanity-io/sanity-plugin-content-calendar#9]
Offending lines:

https://github.com/sanity-io/sanity-plugin-content-calendar/blob/4b3f2b4a4ffeabdcb130cb8847a0fa44eccbe21d/src/hooks.js#L30

https://github.com/sanity-io/sanity-plugin-content-calendar/blob/4b3f2b4a4ffeabdcb130cb8847a0fa44eccbe21d/src/hooks.js#L72

The fix is trivial, but I'm not sure what version to use. Otherwise happy to make a PR

**Comment by runeb** [comment]
@alexeygolev Any version would work, current date or previous dates. Appreciate PR!

https://www.sanity.io/help/studio-client-specify-api-version#e9356f5ca5b1

**Comment by runeb** [comment]
Solved in #12
